### ISSUE TITLE
Add MIT License

### ISSUE THREAD

**Issue by stevenfollis** [GSIAzureCOE/Art-of-the-Possible#1]

**Comment by jwetty** [comment]
What did I buy?

Jeff Wettlaufer | Architect Manager | EMEA Lead | GSI Azure Center of Excellence |

**Comment by stevenfollis** [comment]
Distributing out some ToDos :)

**Comment by jwetty** [comment]
You are so bossy.  You need a scarf.

Jeff Wettlaufer | Architect Manager | EMEA Lead | GSI Azure Center of Excellence |
